generation: 1
translation_map:
  jammy: 'Ubuntu Jammy'
  installType: 'Install type'
sets:
  # Makes everything but install files and sdf worlds
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: false
        name: install
      - isMatch: false
        name: src
      - isMatch: false
        labels:
          - sdf worlds
    dimensions:
      os:
        - Ubuntu Jammy
      buildType:
        - Binary
        - Source
  # Makes only the sdf worlds once
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: true
        labels:
          - sdf worlds
    dimensions:
      os:
        - Ubuntu Jammy
      buildType:
        - Binary
  #####################
  # INSTALL FROM SOURCE
  #####################
  # Install on Ubuntu from source
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: true
        name: ubuntu
      - isMatch: true
        name: src
      - isMatch: true
        labels:
          - docs
    dimensions:
      os:
        - Ubuntu Jammy
      buildType:
        - Source
  # Install on MacOS from source
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: true
        name: osx
      - isMatch: true
        name: src
      - isMatch: true
        labels:
          - docs
    dimensions:
      os:
        - MacOS
      buildType:
        - Source
  # Install on Windows from source
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: true
        name: windows
      - isMatch: true
        name: src
      - isMatch: true
        labels:
          - docs
    dimensions:
      os:
        - Windows
      buildType:
        - Source
  #####################
  # INSTALL FROM BINARIES
  #####################
  # Install on Ubuntu from from binaries
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: false
        name: src
      - isMatch: true
        name: install_ubuntu
      - isMatch: true
        labels:
          - docs
    dimensions:
      os:
        - Ubuntu Jammy
      buildType:
        - Binary

  # Install on macOS from from binaries
  - filters:
      - isMatch: true
        labels:
          - harmonic
      - isMatch: false
        name: src
      - isMatch: true
        name: install_osx
      - isMatch: true
        labels:
          - docs
    dimensions:
      os:
        - MacOS
      buildType:
        - Binary
