test_cases_builders:
- name: main
  description: Makes everything but install files and sdf worlds
  set:
  - !Include
    all_labels: null
    negate: false
  - !Exclude
    any_names: [install, src]
    all_labels: [docs]
    negate: false
  - !Exclude
    all_labels: [sdf worlds]
    negate: false
  - !Exclude
    all_labels: [sdf_tutorials]
    negate: false
  permutations:
    os:
    - MacOS
    - Ubuntu Jammy
    - Windows

- name: sdf_worlds
  description: Makes only the sdf worlds for MacOS and Ubuntu binaries
  set:
  - !Include
    all_labels: [sdf worlds]
    negate: false
  permutations:
    os:
      - Any

- name: install_source_ubuntu
  description: Install on Ubuntu from source
  set:
  - !Include
    all_labels: [docs]
    any_names: [ubuntu_src]
    negate: false
  permutations:
    os:
    - Ubuntu Jammy
    buildType:
    - Source

- name: install_source_macos
  description: Install on MacOS from source
  set:
  - !Include
    all_labels: [docs]
    any_names: [osx_src]
    negate: false
  permutations:
    os:
    - MacOS
    buildType:
    - Source

- name: install_source_win
  description: Install on Windows from source
  set:
  - !Include
    all_labels: [docs]
    any_names: [windows_src]
    negate: false
  permutations:
    os:
    - Windows
    buildType:
    - Source


- name: install_binaries_ubuntu
  description: Install on Ubuntu from binaries
  set:
  - !Include
    all_labels: [docs]
    any_names: [install_ubuntu]
    negate: false
  - !Exclude
    all_labels: [docs]
    any_names: [src]
    negate: false
  permutations:
    os:
    - Ubuntu Jammy
    buildType:
    - Binary

- name: install_binaries_macos
  description: Install on MacOS from binaries
  set:
  - !Include
    all_labels: [docs]
    any_names: [install_osx]
    negate: false
  - !Exclude
    all_labels: [docs]
    any_names: [src]
    negate: false
  permutations:
    os:
    - MacOS
    buildType:
    - Binary
